In [1]:
import pandas as pd

df = pd.read_excel("Intersection Data/sample_data.xlsx", index_col=0)
df

east_recto_2_0  east_recto_2_1  east_recto_2_2  \
west_recto_0_0                   0               0               0   
west_recto_0_1                   0               0               0   
west_recto_0_2                   0               0               0   
south_corrales_1_0              60              60              60   
south_corrales_1_1              60              60              60   
east_recto_1_0                  60              60              60   
east_recto_1_1                  60              60              60   
north_corrales_0_0              60              60              60   
north_corrales_0_1              60              60              60   

                    north_corrales_1_0  north_corrales_1_1  west_recto_1_0  \
west_recto_0_0                      60                  60              60   
west_recto_0_1                      60                  60              60   
west_recto_0_2                      60                  60              60   
south_corrales_1_0                   0                   0               0   
south_corrales_1_1                   0                   0               0   
east_recto_1_0                       0                   0               0   
east_recto_1_1                       0                   0               0   
north_corrales_0_0                   0                   0               0   
north_corrales_0_1                   0                   0               0   

                    west_recto_1_1  south_corrales_2_0  south_corrales_2_1  
west_recto_0_0                  60                  60                  60  
west_recto_0_1                  60                  60                  60  
west_recto_0_2                  60                  60                  60  
south_corrales_1_0              60                  60                  60  
south_corrales_1_1              60                  60                  60  
east_recto_1_0                  60                  60                  60  
east_recto_1_1                  60                  60                  60  
north_corrales_0_0              60                  60                  60  
north_corrales_0_1              60                  60                  60

In [2]:
from_val = []
to_val = []
count = []
for idx_r, row in enumerate(df.index.to_list()):
    for idx_c, column in enumerate(df.columns.to_list())[0]:
        print(row, column)
        from_val.append(df.index.to_list()[idx_r])
        to_val.append(df.columns.to_list()[idx_c])
        count.append(df.iloc[idx_r, idx_c])

new_df = pd.DataFrame({'From': from_val,'To': to_val, 'Count': count})
new_df

west_recto_0_0 east_recto_2_0
west_recto_0_0 east_recto_2_1
west_recto_0_0 east_recto_2_2
west_recto_0_0 north_corrales_1_0
west_recto_0_0 north_corrales_1_1
west_recto_0_0 west_recto_1_0
west_recto_0_0 west_recto_1_1
west_recto_0_0 south_corrales_2_0
west_recto_0_0 south_corrales_2_1
west_recto_0_1 east_recto_2_0
west_recto_0_1 east_recto_2_1
west_recto_0_1 east_recto_2_2
west_recto_0_1 north_corrales_1_0
west_recto_0_1 north_corrales_1_1
west_recto_0_1 west_recto_1_0
west_recto_0_1 west_recto_1_1
west_recto_0_1 south_corrales_2_0
west_recto_0_1 south_corrales_2_1
west_recto_0_2 east_recto_2_0
west_recto_0_2 east_recto_2_1
west_recto_0_2 east_recto_2_2
west_recto_0_2 north_corrales_1_0
west_recto_0_2 north_corrales_1_1
west_recto_0_2 west_recto_1_0
west_recto_0_2 west_recto_1_1
west_recto_0_2 south_corrales_2_0
west_recto_0_2 south_corrales_2_1
south_corrales_1_0 east_recto_2_0
south_corrales_1_0 east_recto_2_1
south_corrales_1_0 east_recto_2_2
south_corrales_1_0 north_corrales_1_0
so

From                  To  Count
0       west_recto_0_0      east_recto_2_0      0
1       west_recto_0_0      east_recto_2_1      0
2       west_recto_0_0      east_recto_2_2      0
3       west_recto_0_0  north_corrales_1_0     60
4       west_recto_0_0  north_corrales_1_1     60
..                 ...                 ...    ...
76  north_corrales_0_1  north_corrales_1_1      0
77  north_corrales_0_1      west_recto_1_0      0
78  north_corrales_0_1      west_recto_1_1     60
79  north_corrales_0_1  south_corrales_2_0     60
80  north_corrales_0_1  south_corrales_2_1     60

[81 rows x 3 columns]

In [5]:
new_df.sort_values(by='Count')

From                  To  Count
0       west_recto_0_0      east_recto_2_0      0
31  south_corrales_1_0  north_corrales_1_1      0
32  south_corrales_1_0      west_recto_1_0      0
39  south_corrales_1_1  north_corrales_1_0      0
41  south_corrales_1_1      west_recto_1_0      0
..                 ...                 ...    ...
25      west_recto_0_2  south_corrales_2_0     60
24      west_recto_0_2      west_recto_1_1     60
51      east_recto_1_0      west_recto_1_1     60
79  north_corrales_0_1  south_corrales_2_0     60
80  north_corrales_0_1  south_corrales_2_1     60

[81 rows x 3 columns]

||Vehicle_Class| Begin| End| From| To| Count||

In [3]:
from_val, to_val, count_val = new_df.iloc[0,:].to_list()

from IPython.display import display

display(from_val, to_val, count_val)

'west_recto_0_0'

'east_recto_2_0'

0

In [6]:
txt = f'<edgeRelation from="{from_val}" to="{to_val}" count="{count_val}"/>'
txt

'<edgeRelation from="west_recto_0_0" to="east_recto_2_0" count="0"/>'

In [2]:
import pandas as pd


xl_file = pd.ExcelFile("TVC Summary.xlsx")
xl_file.sheet_names
df = pd.read_excel("TVC Summary.xlsx", sheet_name=xl_file.sheet_names[0])
df

Time  cars_SUV  motorcycles_scooters  taxi  buses  \
0     5:00am - 6:00am        13                    19     4    NaN   
1     6:00am - 7:00am        14                    47    20    NaN   
2     7:00am - 8:00am        49                    89    24    NaN   
3     8:00am - 9:00am       116                   143    27    NaN   
4    9:00am - 10:00am       128                   155    28    NaN   
5   10:00am - 11:00am       137                   134    40    NaN   
6   11:00am - 12:00nn       126                   129    30    NaN   
7    12:00nn - 1:00pm        93                    84    33    NaN   
8     1:00pm - 2:00pm       138                   120    34    NaN   
9     2:00pm - 3:00pm       139                   111    19    NaN   
10    3:00pm - 4:00pm       153                   178    22    NaN   
11    4:00pm - 5:00pm       143                   161    31    NaN   
12    5:00pm - 6:00pm       151                   191    27    NaN   
13    6:00pm - 7:00pm       131                   168    24    1.0   
14    7:00pm - 8:00pm        87                    83    19    1.0   
15              Total      1618                  1812   382    2.0   

    smallTrucks  largeTrucks  bicycle_tricycle  jeepney  motorela  others  \
0             2          NaN                 2      NaN        44     1.0   
1             1          NaN                 7      NaN        88     2.0   
2             2          1.0                 8      NaN       143     3.0   
3             6          NaN                 9      NaN       236     7.0   
4             9          NaN                 7      NaN       204     1.0   
5             8          1.0                 5      NaN       178     3.0   
6             6          1.0                14      NaN       193     4.0   
7             5          NaN                 3      NaN       185     NaN   
8            11          NaN                 6      NaN       171     NaN   
9            12          NaN                 1      NaN       170     3.0   
10            9          NaN                 6      NaN       160     1.0   
11           16          NaN                 4      NaN       155     NaN   
12            9          NaN                 5      NaN       157     NaN   
13            4          NaN                 8      NaN       156     1.0   
14            1          NaN                 4      NaN       124     NaN   
15          101          3.0                89      NaN      2364    26.0   

    Total  
0      85  
1     179  
2     319  
3     544  
4     532  
5     506  
6     503  
7     403  
8     480  
9     455  
10    529  
11    510  
12    540  
13    493  
14    319  
15   6397

In [3]:
sample_df = df.iloc[:-1,:-1]
sample_df

Time  cars_SUV  motorcycles_scooters  taxi  buses  \
0     5:00am - 6:00am        13                    19     4    NaN   
1     6:00am - 7:00am        14                    47    20    NaN   
2     7:00am - 8:00am        49                    89    24    NaN   
3     8:00am - 9:00am       116                   143    27    NaN   
4    9:00am - 10:00am       128                   155    28    NaN   
5   10:00am - 11:00am       137                   134    40    NaN   
6   11:00am - 12:00nn       126                   129    30    NaN   
7    12:00nn - 1:00pm        93                    84    33    NaN   
8     1:00pm - 2:00pm       138                   120    34    NaN   
9     2:00pm - 3:00pm       139                   111    19    NaN   
10    3:00pm - 4:00pm       153                   178    22    NaN   
11    4:00pm - 5:00pm       143                   161    31    NaN   
12    5:00pm - 6:00pm       151                   191    27    NaN   
13    6:00pm - 7:00pm       131                   168    24    1.0   
14    7:00pm - 8:00pm        87                    83    19    1.0   

    smallTrucks  largeTrucks  bicycle_tricycle  jeepney  motorela  others  
0             2          NaN                 2      NaN        44     1.0  
1             1          NaN                 7      NaN        88     2.0  
2             2          1.0                 8      NaN       143     3.0  
3             6          NaN                 9      NaN       236     7.0  
4             9          NaN                 7      NaN       204     1.0  
5             8          1.0                 5      NaN       178     3.0  
6             6          1.0                14      NaN       193     4.0  
7             5          NaN                 3      NaN       185     NaN  
8            11          NaN                 6      NaN       171     NaN  
9            12          NaN                 1      NaN       170     3.0  
10            9          NaN                 6      NaN       160     1.0  
11           16          NaN                 4      NaN       155     NaN  
12            9          NaN                 5      NaN       157     NaN  
13            4          NaN                 8      NaN       156     1.0  
14            1          NaN                 4      NaN       124     NaN

In [9]:
sample_df = df.loc[~(df['Time'] == 'Total')]
sample_df.iloc[:,:]

Time  cars_SUV  motorcycles_scooters  taxi  buses  \
0     5:00am - 6:00am        13                    19     4    NaN   
1     6:00am - 7:00am        14                    47    20    NaN   
2     7:00am - 8:00am        49                    89    24    NaN   
3     8:00am - 9:00am       116                   143    27    NaN   
4    9:00am - 10:00am       128                   155    28    NaN   
5   10:00am - 11:00am       137                   134    40    NaN   
6   11:00am - 12:00nn       126                   129    30    NaN   
7    12:00nn - 1:00pm        93                    84    33    NaN   
8     1:00pm - 2:00pm       138                   120    34    NaN   
9     2:00pm - 3:00pm       139                   111    19    NaN   
10    3:00pm - 4:00pm       153                   178    22    NaN   
11    4:00pm - 5:00pm       143                   161    31    NaN   
12    5:00pm - 6:00pm       151                   191    27    NaN   
13    6:00pm - 7:00pm       131                   168    24    1.0   
14    7:00pm - 8:00pm        87                    83    19    1.0   

    smallTrucks  largeTrucks  bicycle_tricycle  jeepney  motorela  others  \
0             2          NaN                 2      NaN        44     1.0   
1             1          NaN                 7      NaN        88     2.0   
2             2          1.0                 8      NaN       143     3.0   
3             6          NaN                 9      NaN       236     7.0   
4             9          NaN                 7      NaN       204     1.0   
5             8          1.0                 5      NaN       178     3.0   
6             6          1.0                14      NaN       193     4.0   
7             5          NaN                 3      NaN       185     NaN   
8            11          NaN                 6      NaN       171     NaN   
9            12          NaN                 1      NaN       170     3.0   
10            9          NaN                 6      NaN       160     1.0   
11           16          NaN                 4      NaN       155     NaN   
12            9          NaN                 5      NaN       157     NaN   
13            4          NaN                 8      NaN       156     1.0   
14            1          NaN                 4      NaN       124     NaN   

    Total  
0      85  
1     179  
2     319  
3     544  
4     532  
5     506  
6     503  
7     403  
8     480  
9     455  
10    529  
11    510  
12    540  
13    493  
14    319

In [23]:
filepath = "TVC Summary.xlsx"
xlsx_file = pd.ExcelFile(filepath)
sht_names = xlsx_file.sheet_names

In [ ]:
from IPython.display import display

for sheet in sht_names:
    df = pd.read_excel(filepath, sheet_name=sheet)
    from_val = sheet.split('_')[0]
    to_val = sheet.split('_')[1]
    df = df.iloc[:-1,:-1] #eliminate total
    sample_df = some_func(askfllsf)
    display(df.head(5))

In [48]:
import pandas as pd

df = pd.read_csv("datadata.csv", index_col=0)
df.head(5)

Time                 class  Count   From    To
0  5:00am - 6:00am              cars_SUV   13.0  North  West
1  5:00am - 6:00am  motorcycles_scooters   19.0  North  West
2  5:00am - 6:00am                  taxi    4.0  North  West
3  5:00am - 6:00am                 buses    NaN  North  West
4  5:00am - 6:00am           smallTrucks    2.0  North  West

In [49]:
def time_convert(df):
    #Seperates Time column to 'Begin' and 'End'
    df["Begin"] = df['Time'].apply(lambda x: x.split(" - ")[0])
    df["End"] = df['Time'].apply(lambda x: x.split(" - ")[1])
    df = df.drop(columns=['Time'])

    #Puts 'Begin' and 'End' in the front of the dataframe
    reorganized_columns = df.columns[-2:].to_list() + df.columns[0:len(df.columns)-2].to_list()
    df = df[reorganized_columns]

    #fill null values with 0
    df.fillna(0, inplace=True)

    #Change all instances of 12:00nn to correct 12:00pm
    df.loc[df['Begin'] == '12:00nn'] = '12:00pm'
    df.loc[df['End'] == '12:00nn'] = '12:00pm'

    #Create a function that converts string time to seconds 
    def time_to_seconds(val):
        val = pd.to_datetime(val).to_pydatetime()
        seconds = val.timestamp()
        return int(seconds)

    #applies previous function
    df["Begin"] = df['Begin'].apply(time_to_seconds)
    df["End"] = df['End'].apply(time_to_seconds)

    #Modify time to start at 0
    time_start = df["Begin"][0]
    df["Begin"] = df["Begin"] - time_start
    df["End"] = df["End"] - time_start


=

    return df



In [5]:
all_df = []
for jcts in all_jcts:
    df = pd.read_excel(jcts, sheet_name="TVC")
    df = cleaning(df) #DO NOT INCLUDE DIRECTORY SHEET

    xl_obj = pd.read_excel("Di.xlsx", sheet_name="Directory")
    xl_obj = convert_to_dict(xl_obj)
    
    df = convert_direction(df, xl_obj)
    all_df.append(df)

['Luna', 'Corrales']

In [3]:
import numpy as np

x = [[1,2],[3,4]]
y = np.array([])

for i in x:
    y = np.concatenate([y,i])

y

array([1., 2., 3., 4.])

In [2]:
import numpy as np

x = [1,2]
y = [3,4]
z = [5,6]

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6])

In [ ]:
import pandas as pd

df = pd.read_csv("FINALDUMMY.csv")

In [2]:
import numpy as np
x = []
for i in range(5):
    start = i*5
    end = (i+1)*5
    arry = np.arange(start,end,1)
    x.append(arry.tolist())

x

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [7]:
new_arry = np.array([])
for i in x:
    i = np.array(i)
    new_arry = np.concatenate([new_arry,i])

new_arry

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [1]:
import gym  #noqa

In [6]:
env = gym.make('CartPole-v1')
obs = env.reset()
print(env.step(env.action_space.sample()))

(array([-0.04421936,  0.15922242, -0.04663465, -0.34367388], dtype=float32), 1.0, False, {})
